### ISSUE TITLE
Parameters in WCM

### ISSUE THREAD

**Issue by ajigeo** [multiply-org/forward-operators#3]
Can you explain how the parameters A,B,C,D & E are calculated in the water cloud model?

**Comment by McWhity** [comment]
The MULTIPLY platform is under development. Currently, just the basic code of the the water cloud model with parameters found in the literature is implemented. This serves so far for the testing purposes of the platform. It is planned to calibrate the parameters for the Munich-North-Isar (MNI) test-site in Germany.
